name: cpp-simple

# course
deadlines: hard
second_deadline_max: 0.3

# checker
system: script
layout: any
executor: sandbox
templates: search
tester_args:
  default_build_cmd: "${ROOT_DIR}/build.sh test_$(basename $PWD)"
  default_test_cmd: "cd ${BUILD_DIR} && env -i ./test_$(basename $OLDPWD)"
public_patterns: ["**", "**/.gitignore"]

# gitlab
course_group: cpp-simple
public_repo: cpp-simple/public-2023-fall
students_group: cpp-simple/students-2023-fall

# manytask
manytask_url: https://cpp.manytask.org
